cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('about', views.about, name='about'),
    path('contacts', views.contacts, name='contacts'),
    path('contacts', views.contacts, name='contacts'),
    path('search', views.search, name='search'),

]

shop/models.py
from django.urls import reverse
from django.db import models
from pytils.translit import slugify


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    product_name = models.CharField(max_length=200, db_index=True)
    image = models.URLField(blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.CharField(max_length=3, db_index=True, blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
import json
import shop.bd_form
import shop.price_form


def about(request):
    return render(request, 'shop/about.html')


def contacts(request):
    return render(request, 'shop/contacts.html')


def get_base():
    """Function get data from base.txt"""
    with open('Price/base.txt') as fh:
        base = json.load(fh)
    return base


def data_refresh(base: dict):
    """Function create instances of Category and Product from base"""
    for key, val in base.items():
        try:
            Category.objects.get(name=key)
            print(f'"{key}" - category exists!')
        except:
            Category(name=key).save()
            print(f'"{key}" - category created!')
        finally:
            for equip, desc in val.items():
                try:
                    inst = Product.objects.get(name=equip)
                    inst.price = desc[1]
                    inst.stock = desc[2]
                    inst.save()
                    print(f'Stock balance and price for {equip} updated.')
                except:
                    cat = Category.objects.get(name=key)
                    if len(desc) == 5:
                        Product(category=cat, name=equip, product_name=desc[0],
                                price=desc[1], stock=desc[2]).save()
                        print(f'{equip} product card created ')
                    else:
                        if len(desc[6]) == 0:
                            Product(category=cat, name=equip, product_name=desc[0], description=desc[5],
                                    price=desc[1], stock=desc[2]).save()
                            print(f'{equip} product card created ')
                        else:
                            Product(category=cat, name=equip, product_name=desc[0], image=desc[6][0],
                                    description=desc[5], price=desc[1], stock=desc[2]).save()
                            print(f'{equip} product card created ')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 15)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        products = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop/product/list.html',
                  {'page': page,
                   'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def run():
    """For price download and image, desc update."""
    shop.price_form.directory_cleaning()
    outfilename = shop.price_form.file_download("https://microinform.by/downloads/m_price.rar")
    shop.price_form.rar_unpacking(outfilename)
    data_dict = shop.price_form.price_conversion(percent=50)
    shop.price_form.price_create(data_dict)
    base_for_save = shop.bd_form.dict_convert(shop.bd_form.add_data(data_dict))
    shop.bd_form.save_base(base_for_save)
    data_refresh(base_for_save)

# run()


def search(request):
    query = request.GET.get('q')
    search_list = Product.objects.filter(Q(name__icontains=query) | Q(product_name__icontains=query), available=True)
    return render(request, 'shop/search_results.html',
                  {'products': search_list})

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}О компании{% endblock %}

{% block content %}
    <h1>О компании</h1>
    <link href="{% static "css/shop/about.css" %}" rel="stylesheet">
    <div>
        <p class="text-about">Так называлась 15-я глава сатирического романа И. Ильфа и Е. Петрова "Золотой теленок" (1931), в которой рассказывается о фиктивном предприятии – "конторе по заготовке рогов и копыт", организованной пройдохой и мошенником Остапом Бендером. Выражение "рога и копыта", ставшее крылатым, применяется как образное определение ловко организованных мошеннических предприятий.</p>
    </div>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}Horns&hooves{% endblock %}</title>
    <link href="{% static "css/shop/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo"><b>Horns&hooves LLC</b></a>
    </div>
    <span class="search">
        <form class="s1" action="/search" method="get">
            <input class="s2" name="q" type="text" placeholder="Поиск...">
            <button class="b1" type="submit">Найти</button>
        </form>
    </span>
    <div id="subheader">
        <div class="cart">
            {% if request.user.is_authenticated %}
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                Ваша корзина:<br>
                <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} позиции{{ total_items|pluralize }},
                    {{ cart.get_total_price }} BYN
                </a>
                {% else %}
                    Ваша корзина пуста.
                {% endif %}
                {% endwith %}
            {% endif %}
        </div>
        <span class="user">
        {% if request.user.is_authenticated %}
            Привет, {{ request.user.username }},<br>
            <a href="{% url "logout" %}">Выход</a>
            <a href="{% url "password_change" %}">| Сменить пароль</a>
        {% else %}
            <a href="{% url "login" %}">Войти</a>
        {% endif %}
      </span>
        <link href="{% static "css/shop/mybtn.css" %}" rel="stylesheet">
        <div id="position">
            <a href="/" class="button">Главная</a>
            <a href="/about" class="button" >О компании</a>
            <a href="/contacts" class="button">Контакты</a>
            <a href="static/price.xls" class="button">Прайс-лист</a>
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

shop/templates/shop/contacts.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Контакты{% endblock %}
{% block content %}
    <h1>Контакты</h1>
    <div id="about">
        <p>"Horns and hooves" LLC</p>
        <p>200000, г. Минск, пр-т Машерова, 1</p>
        <p>р/с №BY00XXXX000000000000000000000001 в ЗАО «Альфа-Банк»</p>
        <p>Республика Беларусь, 220013, г. Минск, ул. Сурганова, 43-47.</p>
        <p>Тел. факс: +375 (17) 200-00-00</p>
        <p>e-mail: info@myshop.by</p>
        <link href="{% static "css/shop/map.css" %}" rel="stylesheet">
        <div id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d550.8245053647443!2d27.576496225722405!3d53.91069628212707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dbcfbb632e5ad1%3A0xdf6d492d4a3241c9!2z0L_RgNC-0YHQvy4g0JzQsNGI0LXRgNC-0LLQsCAxLCDQnNC40L3RgdC6!5e1!3m2!1sru!2sby!4v1644253957786!5m2!1sru!2sby" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>
{% endblock %}

shop/templates/shop/pagination.html
<div class="pagination">
  <span class="step-links">
  {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">Назад</a>
  {% endif %}
  <span class="current">
    Страница {{ page.number }} из {{ page.paginator.num_pages }}.
  </span>
  {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Вперед</a>
  {% endif %}
  </span>
</div>

shop/templates/shop/search_results.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
<link href="{% static "css/shop/list.css" %}" rel="stylesheet">
<div id="main" class="product-list">
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a class="text-prod-list" href="{{ product.get_absolute_url }}"><b>{{ product.name }}</b> {{product.product_name}}</a>
        {{ product.price }} BYN
    </div>
    {% empty %}
    <h3 style="color: #2D4B5E" >По вашему запросу ничего не найдено:(</h3>
    <br>
    {% endfor %}
</div>
{% endblock %}